branches:
  only:
    - master
    
hosts:
  api.nuget.org: 93.184.221.200

environment:
  access_token:
    # EDIT the encrypted version of your GitHub access token
    secure: qy4AqVCB780JU08gAz1Zs9Nk6pL940FklM5m5F7AwXG9MC6mEmGImsIRbpkqd68z

install:
  - git submodule update --init --recursive
  - mkdir ..\Wyam
  - mkdir ..\wwwroot
  # Fetch the latest version of Wyam 
  - "curl -s https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE -o ..\\Wyam\\wyamversion.txt"
  - set /P WYAMVERSION=< ..\Wyam\wyamversion.txt
  - echo %WYAMVERSION%
  # Get and unzip the latest version of Wyam
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/$env:WYAMVERSION/Wyam-$env:WYAMVERSION.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r
  - pwd
  - ls
  - cd ..

build:
  publish_wap: true
  verbosity: minimal


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
# pushing entire folder as a zip archive
  - path: 'wwwroot\**\*.*'
    name: output

deploy:
- provider: FTP
  host: noknok.pl
  protocol: ftp
  username: jnaughton-AppVeyorBlog
  password:
    secure: oNiPzH/wQeUgfW1lGHhFDzhhL1gLaSZ+9JD2ovtmW/k=
  artifact: output

build_script:
  - Wyam\wyam noknokwyamblog --recipe Blog --theme CleanBlog --output wwwroot
  - pwd
  - ls
  - xcopy noknokwyamblog\wwwroot wwwroot\ /Esy
  - ls wwwroot


on_success:
  - pwd
  - ls
  - cd noknokwyamblog 
  # Switch branches to gh-pages, clean the folder, copy everything in from the Wyam output, and commit/push
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  # EDIT your Git email and name
  #- git config --global user.email $env:op_build_user_email
  #- git config --global user.name $env:op_build_user
  - git config --global user.email "mark.burton@zither-it.co.uk"
  - git config --global user.name "Mark Burton"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout gh-pages
  - git rm -rf .
  - xcopy ..\wwwroot . /E
  # EDIT your domain name or remove if not using a custom domain
  #- echo wyam.io > CNAME
  # EDIT the origin of your repository - have to reset it here because AppVeyor pulls from SSH, but GitHub won't accept SSH pushes
  - git remote set-url origin https://github.com/MarkZither/NokNokWyamBlog.git
  - git add -A
  - git commit -a -m "Commit from AppVeyor"
  - git push